# Grafana Datasource Configuration for Prometheus
# 
# Configures Prometheus as the primary data source
# Per requirements.md: Complete implementation, no placeholders.

apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true
    jsonData:
      httpMethod: POST
      manageAlerts: true
      prometheusType: Prometheus
      prometheusVersion: "2.40.0"
      cacheLevel: 'High'
      disableMetricsLookup: false
      incrementalQuerying: true
      exemplarTraceIdDestinations:
        - name: trace_id
          datasourceUid: jaeger
    secureJsonData: {}
  
  # PostgreSQL datasource for direct database queries
  - name: PostgreSQL
    type: postgres
    access: proxy
    url: postgres:5432
    database: mcp_routing
    user: mcp_user
    secureJsonData:
      password: mcp_secure_password_2024
    jsonData:
      sslmode: disable
      maxOpenConns: 10
      maxIdleConns: 2
      connMaxLifetime: 14400
      postgresVersion: 1500
      timescaledb: false
    editable: true